### ISSUE TITLE
Library eventually crushes the browser by continuously adding html

### ISSUE THREAD

**Issue by richard-muvirimi** [karimayachi/html-console-output#35]
This is a great library, that meets my use case, but if used where there is a lot of logging to the console the library eventually crushes the browser, probably from the addition of multiple dom elements. The addition of methods to clean up some of the logs or setting a maximum number of items that the console should keep track of might be ideal. I can do a pull request with the suggested changes if given the go-ahead, since there is no CONTRIBUTORS.md file.

**Comment by karimayachi** [comment]
Hi Richard,

You're welcome to make a pull request. I have updated the packages. I'm glad people find use in it. I haven't worked on this library since it served my purpose 5 years ago, but it would be good to keep it up to date.
